version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: snappfood
    network_mode: host
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl/:ro
